name: Actions Status Discord

on: push

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord
        uses: sarisia/actions-status-discord@v1.12.0
        with:
          webhook: ${{ secrets.DISCORD_ACTIONS_WEBHOOK }}
          content: "New changes have been made to the repository."
          title: "Github Actions CI"
          color: 0xfdfd96
          username: Fran
          avatar_url: ${{ secrets.DISCORD_ACTIONS_AVATAR_URL }}
          noprefix: true
